export const LOADING = "LOADING";
export const STORE_ALL_PRODUCTS = "STORE_ALL_PRODUCTS";
export const STORE_ALL_CATEGORIES = "STORE_ALL_CATEGORIES";
export const STORE_ALL_SIZES = "STORE_ALL_SIZES";
